// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using list_item.Data;

#nullable disable

namespace list_item.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240802055802_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("list_item.Models.list", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("lists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deadline = new DateTime(2024, 8, 2, 22, 57, 59, 685, DateTimeKind.Local).AddTicks(4350),
                            Description = "Description 1",
                            Title = "Task 1"
                        },
                        new
                        {
                            Id = 2,
                            Deadline = new DateTime(2024, 8, 3, 22, 57, 59, 685, DateTimeKind.Local).AddTicks(4407),
                            Description = "Description 2",
                            Title = "Task 2"
                        },
                        new
                        {
                            Id = 3,
                            Deadline = new DateTime(2024, 8, 4, 22, 57, 59, 685, DateTimeKind.Local).AddTicks(4410),
                            Description = "Description 3",
                            Title = "Task 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
